config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home' 
  get 'about', to: 'pages#about' 
  get 'testpage', to: 'pages#testpage'
  resources :contacts 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
    protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController 
  def new
  end 
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
 def home
 end 
 
 def about
 end 
 
 def testPage
 end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
   <div class="row">
     <h3 class="text-center">Fale conosco</h3> 
     <div class="col-md-4 col-sm-6 col-sm-offset-3 col-md-offset-4">
       <div class="well">
          <%= form_for "/contacts" do |f| %>
          <div class="form-group">
             <%= f.label :nome %>
             <%= f.text_field :nome, class:'form-control' %>
          </div>
         
          <div class="form-group">
             <%= f.label :email %>
             <%= f.text_field :email, class:'form-control' %>
          </div>
         
          <div class="form-group">
             <%= f.label :commentarios %>
             <%= f.text_area :comentarios, class:'form-control' %> 
          </div>
         
           <%= f.submit 'Enviar', class:'btn btn-primary' %>
           <% end %> 
       </div>
     </div> 
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>Meu Site</title>
     <%= csrf_meta_tags %>
     
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@500&family=Ubuntu:ital,wght@0,300;1,500&display=swap" rel="stylesheet">
     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
   </head>
   
   <body>
     <nav class="navbar navbar-expand-md navbar-static-top" role="navigation">
       <div class='container'>
         <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <%= link_to root_path, class:"navbar-brand" do %>
           <i class="fa fa-code-fork"></i>
           Matest 
           <% end %>
           
         </div>
         <div class="collapse navbar-collapse" id="main-nav-collapse">
           <ul class="nav navbar-nav navbar-right">
             <li class="nav-item dropdown"><%= link_to "Sobre", about_path %></li>
             <li class="nav-item dropdown"><%= link_to "Testes", testpage_path %></li>
           </ul> 
         </div><!-- /.navbar-collapse --> 
       </div>
     </nav>
     
     <%= yield %> 
      
     <footer>
      <div class="text-center">
       <nav aria-label="Page navigation">
         <ul class="pagination">
           <li>
             <a href="#" aria-label="Previous">
               <span aria-hidden="true">&laquo;</span>
             </a>
           </li>
           <li><a href="#">1</a></li>
           <li><a href="#">2</a></li>
           <li><a href="#">3</a></li>
           <li><a href="#">4</a></li>
           <li><a href="#">5</a></li>
           <li>
             <a href="#" aria-label="Next">
               <span aria-hidden="true">&raquo;</span>
             </a>
           </li>
         </ul>
       </nav>
      </div>
     </footer>
   </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-center">Sobre nós</h1> 

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>Bem vindo!</h1>
  <h3>Texto genérico menor e centralizado</h3>
</div>

app/views/pages/testpage.html.erb
<div class="text-center testCSS">
     <h1>Página para testar CSS</h1>
     <br>
     <br>
     <br> 
     <a class="nulllink">Clique aqui!</a>
</div>
<br>
    <div class="grid-container">
      <div class="grid-item">1</div>
      <div class="grid-item">2</div>
      <div class="grid-item">3</div>
      <div class="grid-item">4</div>
      <div class="grid-item">5</div>
      <div class="grid-item">6</div>
      <div class="grid-item">7</div>
      <div class="grid-item">8</div>
      <div class="grid-item">9</div>
    </div>
<br>